export const ProductItems = [
    {
        id:1,
        name:"Cat",
        age:"Newborn",
        price:250.68,
        imgPet:"petCat.png",
        statuses: ["statusProductM.png","statusProductR.png"],
        rare:"blue",
    },
    {
        id:2,
        name:"Liama",
        age:"Newborn",
        price:200.68,
        imgPet:"petLama.png",
        statuses: ["statusProductF.png","statusProductN.png"],
        rare:"red",
    },
    {
        id:3,
        name:"Cat",
        age:"Newborn",
        price:250.68,
        imgPet:"petCat.png",
        statuses: ["statusProductF.png","statusProductR.png"],
        rare:"blue",
    },
    {
        id:4,
        name:"Liama",
        age:"Newborn",
        price:200.68,
        imgPet:"petLama.png",
        statuses: ["statusProductN.png","statusProductR.png"],
        rare:"red",
    },
    {
        id:5,
        name:"Diamond Ladybag",
        age:"Newborn",
        price:200.68,
        imgPet:"petShuk.png",
        statuses: ["statusProductM.png","statusProductR.png"],
        rare:"green",
    },
    {
        id:6,
        name:"Red Panda",
        age:"Newborn",
        price:199.68,
        imgPet:"petLiss.png",
        statuses: ["statusProductF.png","statusProductR.png","statusProductM.png"],
        rare:"violet",
    },
    {
        id:7,
        name:"Cat",
        age:"Newborn",
        price:199.68,
        imgPet:"petCat.png",
        statuses: ["statusProductF.png","statusProductR.png"],
        rare:"blue",
    },
    {
        id:8,
        name:"Liama",
        age:"Newborn",
        price:199.68,
        imgPet:"petLama.png",
        statuses: ["statusProductF.png","statusProductN.png","statusProductM.png"],
        rare:"red",
    },
    {
        id:9,
        name:"Cat",
        age:"Newborn",
        price:250.68,
        imgPet:"petCat.png",
        statuses: ["statusProductM.png","statusProductR.png"],
        rare:"blue",
    },
    {
        id:10,
        name:"Liama",
        age:"Newborn",
        price:200.68,
        imgPet:"petLama.png",
        statuses: ["statusProductF.png","statusProductN.png"],
        rare:"red",
    },
    {
        id:11,
        name:"Cat",
        age:"Newborn",
        price:250.68,
        imgPet:"petCat.png",
        statuses: ["statusProductF.png","statusProductR.png"],
        rare:"blue",
    },
    {
        id:12,
        name:"Liama",
        age:"Newborn",
        price:200.68,
        imgPet:"petLama.png",
        statuses: ["statusProductN.png","statusProductR.png"],
        rare:"red",
    },
    {
        id:13,
        name:"Diamond Ladybag",
        age:"Newborn",
        price:200.68,
        imgPet:"petShuk.png",
        statuses: ["statusProductM.png","statusProductR.png"],
        rare:"green",
    },
    {
        id:14,
        name:"Red Panda",
        age:"Newborn",
        price:199.68,
        imgPet:"petLiss.png",
        statuses: ["statusProductF.png","statusProductR.png","statusProductM.png"],
        rare:"violet",
    },
    {
        id:15,
        name:"Cat",
        age:"Newborn",
        price:199.68,
        imgPet:"petCat.png",
        statuses: ["statusProductF.png","statusProductR.png"],
        rare:"blue",
    },
    {
        id:16,
        name:"Liama",
        age:"Newborn",
        price:199.68,
        imgPet:"petLama.png",
        statuses: ["statusProductF.png","statusProductN.png","statusProductM.png"],
        rare:"red",
    },
    {
        id:17,
        name:"Cat",
        age:"Newborn",
        price:250.68,
        imgPet:"petCat.png",
        statuses: ["statusProductM.png","statusProductR.png"],
        rare:"blue",
    },
    {
        id:18,
        name:"Liama",
        age:"Newborn",
        price:200.68,
        imgPet:"petLama.png",
        statuses: ["statusProductF.png","statusProductN.png"],
        rare:"red",
    },
    {
        id:19,
        name:"Cat",
        age:"Newborn",
        price:250.68,
        imgPet:"petCat.png",
        statuses: ["statusProductF.png","statusProductR.png"],
        rare:"blue",
    },
    {
        id:20,
        name:"Liama",
        age:"Newborn",
        price:200.68,
        imgPet:"petLama.png",
        statuses: ["statusProductN.png","statusProductR.png"],
        rare:"red",
    },
    {
        id:21,
        name:"Diamond Ladybag",
        age:"Newborn",
        price:200.68,
        imgPet:"petShuk.png",
        statuses: ["statusProductM.png","statusProductR.png"],
        rare:"green",
    },
    {
        id:22,
        name:"Red Panda",
        age:"Newborn",
        price:199.68,
        imgPet:"petLiss.png",
        statuses: ["statusProductF.png","statusProductR.png","statusProductM.png"],
        rare:"violet",
    },
    {
        id:23,
        name:"Cat",
        age:"Newborn",
        price:199.68,
        imgPet:"petCat.png",
        statuses: ["statusProductF.png","statusProductR.png"],
        rare:"blue",
    },
    {
        id:24,
        name:"Liama",
        age:"Newborn",
        price:179,
        imgPet:"petLama.png",
        statuses: ["statusProductF.png","statusProductN.png","statusProductM.png"],
        rare:"red",
    },
    {
        id:25,
        name:"Cat",
        age:"Newborn",
        price:240,
        imgPet:"petCat.png",
        statuses: ["statusProductM.png","statusProductR.png"],
        rare:"blue",
    },
    {
        id:26,
        name:"Liama",
        age:"Newborn",
        price:172,
        imgPet:"petLama.png",
        statuses: ["statusProductF.png","statusProductN.png"],
        rare:"red",
    },
    {
        id:27,
        name:"Cat",
        age:"Newborn",
        price:132,
        imgPet:"petCat.png",
        statuses: ["statusProductF.png","statusProductR.png"],
        rare:"blue",
    },
    {
        id:28,
        name:"Liama",
        age:"Newborn",
        price:400,
        imgPet:"petLama.png",
        statuses: ["statusProductN.png","statusProductR.png"],
        rare:"red",
    },
    {
        id:29,
        name:"Diamond Ladybag",
        age:"Newborn",
        price:387.68,
        imgPet:"petShuk.png",
        statuses: ["statusProductM.png","statusProductR.png"],
        rare:"green",
    },
    {
        id:30,
        name:"Red Panda",
        age:"Newborn",
        price:799.99,
        imgPet:"petLiss.png",
        statuses: ["statusProductF.png","statusProductR.png","statusProductM.png"],
        rare:"violet",
    },
    {
        id:31,
        name:"Cat",
        age:"Newborn",
        price:155,
        imgPet:"petCat.png",
        statuses: ["statusProductF.png","statusProductR.png"],
        rare:"blue",
    },
    {
        id:32,
        name:"Liama",
        age:"Newborn",
        price:99,
        imgPet:"petLama.png",
        statuses: ["statusProductF.png","statusProductN.png","statusProductM.png"],
        rare:"red",
    },
  ];